backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/assets
public_folder: assets
collections:
  - name: work
    label: Work
    folder: work
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: info, label: Info }
      - { name: githubUrl, label: GitHubUrl }
      - { name: imageUrl, label: ImageUrl }
      - { name: liveUrl, label: LiveUrl }
      - { name: techs, Label: Techs }
